
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 07 12:52:39 CDT 2015
//----------------------------------------------------

package autogen;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_NE = 5;
  public static final int EQUALS = 33;
  public static final int PERIOD = 34;
  public static final int PLUSOP = 41;
  public static final int MINUSOP = 42;
  public static final int OP_GT = 6;
  public static final int LPAREN = 29;
  public static final int PRIVATE = 20;
  public static final int INT = 17;
  public static final int TILDE = 12;
  public static final int INSTANCEOF = 10;
  public static final int STATIC = 23;
  public static final int RPAREN = 30;
  public static final int AND = 39;
  public static final int SEMICOLON = 36;
  public static final int ASTERICK = 40;
  public static final int OP_GE = 2;
  public static final int BANG = 46;
  public static final int COMMA = 37;
  public static final int CLASS = 14;
  public static final int RSLASH = 43;
  public static final int IF = 16;
  public static final int OP_LOR = 9;
  public static final int THIS = 25;
  public static final int EOF = 0;
  public static final int BOOLEAN = 13;
  public static final int RETURN = 22;
  public static final int SUPER = 24;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int OP_LT = 7;
  public static final int PERCENT = 44;
  public static final int PIPE = 38;
  public static final int HAT = 11;
  public static final int NULL = 19;
  public static final int VOID = 26;
  public static final int LITERAL = 48;
  public static final int COLON = 35;
  public static final int OP_LE = 3;
  public static final int LBRACE = 31;
  public static final int ELSE = 15;
  public static final int WHILE = 27;
  public static final int PUBLIC = 21;
  public static final int RBRACE = 32;
  public static final int OP_EQ = 4;
  public static final int QUESTION = 45;
  public static final int ASS_ADD = 28;
  public static final int OP_LAND = 8;
  public static final int INTNUMBER = 49;
  public static final int IDENTIFIER = 47;
}

